# Generated by Django 4.2.7 on 2023-12-02 13:06

from django.db import migrations, models
import django.db.models.deletion
import rental.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('production_year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('daily_rate', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(validators=[])),
                ('end_date', models.DateField(validators=[])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.car')),
            ],
        ),
    ]
