# Generated by Django 4.2.7 on 2023-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Please enter your phone number +2556912345678', max_length=12)),
                ('ID_Number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
