# Generated by Django 4.2.7 on 2023-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ManyToManyField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Electric', 'Electric')], to='rental.car'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.ManyToManyField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], to='rental.car'),
        ),
    ]
