# Generated by Django 4.2.5 on 2023-12-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_car_images_remove_car_fuel_remove_car_gearbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Star-Rental', max_length=30),
        ),
    ]
