# Generated by Django 4.2.5 on 2023-12-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_remove_car_images_car_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(related_name='car_images', to='rental.carimage'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(default='StarRental', max_length=50),
        ),
    ]
