# Generated by Django 4.2.7 on 2023-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_auto_20231204_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='discounted_daily_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
