# Generated by Django 4.2.7 on 2023-12-05 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0011_alter_car_discounted_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
