# Generated by Django 4.2.7 on 2023-12-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_alter_booking_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id_number',
            new_name='CUSTOMER',
        ),
    ]
