# Generated by Django 4.2.7 on 2023-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_rename_id_number_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
