# Generated by Django 5.0 on 2023-12-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_pickuplocation'),
        ('rental', '0017_alter_car_discounted_daily_rate'),
    ]

    operations = [
    ]
