# Generated by Django 4.2.7 on 2023-12-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_merge_20231206_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickupLocation',
        ),
    ]
