# Generated by Django 4.2.7 on 2023-12-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_quicklinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuickLinks',
            new_name='QuickLink',
        ),
    ]
