# Generated by Django 4.2.5 on 2023-12-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_rename_quicklinks_quicklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Tedi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='+355695071059', help_text='Please enter your phone number +2556912345678', max_length=12),
            preserve_default=False,
        ),
    ]
