# Generated by Django 4.2.5 on 2023-12-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
