# Generated by Django 5.0 on 2023-12-10 08:52

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.auth.models import User

class Migration(migrations.Migration):
    
    def populate_user(apps, schema_editor):
        Customer = apps.get_model('rental', 'Customer')
        for customer in Customer.objects.all():
            user_instance = User.objects.get(username='StarRental')
            customer.user = user_instance
            customer.save()
            
    dependencies = [
        ('rental', '0024_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',   
            name='CUSTOMER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rental.customer'),
        ),
    ]
