# Generated by Django 5.0 on 2023-12-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0026_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ID_Number',
        ),
    ]
