# Generated by Django 5.0 on 2023-12-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_remove_customer_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='000000000000', help_text='Please enter your phone number +2556912345678', max_length=12),
        ),
    ]
