# Generated by Django 4.2.7 on 2024-01-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_alter_booking_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickLink',
        ),
        migrations.AddField(
            model_name='customer',
            name='staff_account',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='rental.car'),
        ),
    ]
